/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_hp888_nativeagent_instrument_impl_InstrumentationImpl */

#ifndef _Included_me_hp888_nativeagent_instrument_impl_InstrumentationImpl
#define _Included_me_hp888_nativeagent_instrument_impl_InstrumentationImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_hp888_nativeagent_instrument_impl_InstrumentationImpl
 * Method:    getAllLoadedClasses
 * Signature: ()[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_me_hp888_nativeagent_instrument_impl_InstrumentationImpl_getAllLoadedClasses
  (JNIEnv *, jobject);

/*
 * Class:     me_hp888_nativeagent_instrument_impl_InstrumentationImpl
 * Method:    retransformClasses
 * Signature: ([Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_me_hp888_nativeagent_instrument_impl_InstrumentationImpl_retransformClasses
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     me_hp888_nativeagent_instrument_impl_InstrumentationImpl
 * Method:    getLoadedClasses
 * Signature: (Ljava/lang/ClassLoader;)[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_me_hp888_nativeagent_instrument_impl_InstrumentationImpl_getLoadedClasses
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
